// DuckReliquify event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  AddressExcluded,
  AllocationAdjusted,
  AllocationEditApplied,
  AllocationEditApproved,
  AllocationEditCancelled,
  AllocationEditData,
  AllocationEditExpired,
  AllocationEditProposed,
  AllocationEditRejected,
  BuybackBurned,
  Claimed,
  Deposited,
  DexConfigSet,
  ERC20Rescued,
  ETHRescued,
  Initialized,
  MigrationAborted,
  MigrationApproved,
  MigrationFinalized,
  MigrationProposed,
  MigrationRejected,
  OwnershipTransferStarted,
  OwnershipTransferred,
  PausedSet,
  PlatformWalletSet,
  PoolSeeded,
  Refunded,
  ReliquifyFeeSet,
  ReserveRescued,
  RouteSucceeded,
  RoutesSet,
  SnapshotBatchSubmitted,
  SnapshotFinalized,
  TokenImplSet,
  UniversalRouterUpdated,
  Upgraded,
  VaultFactorySet,
} from "../generated/DuckReliquify/DuckReliquify";
import { Address, BigInt, Bytes, ethereum } from "@graphprotocol/graph-ts";
import { ReliquifyMigration, ReliquifyDeposit, ReliquifyClaim, ReliquifyRefund, ReliquifyBuyback, ReliquifyAllocationEdit, ReliquifyAllocationChange, ReliquifyRescue } from "../generated/schema";
import { DuckToken as DuckTokenTemplate } from "../generated/templates";
import { eventId } from "./admin";
import { newToken } from "./token-meta";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckReliquify";

function migrationEntityId(reliquify: Address, migrationId: BigInt): string {
  return reliquify.toHexString() + "-" + migrationId.toString();
}

export function handleMigrationProposed(event: MigrationProposed): void {
  let m = new ReliquifyMigration(migrationEntityId(event.address, event.params.id));
  m.migrationId = event.params.id;
  m.leader = event.params.leader;
  m.oldToken = event.params.oldToken;
  m.status = "Proposed";
  m.snapshotBatches = 0;
  m.snapshotFinalized = false;
  m.excludedCount = 0;
  m.eligibleSupply = BigInt.zero();
  m.totalDeposited = BigInt.zero();
  m.preSeedDeposited = BigInt.zero();
  m.postSeedDeposited = BigInt.zero();
  m.thresholdReached = false;
  m.totalClaimed = BigInt.zero();
  m.totalRefunded = BigInt.zero();
  m.buybackQuoteSpent = BigInt.zero();
  m.tokensBurned = BigInt.zero();
  m.paused = false;
  m.finalized = false;
  m.reserveRescued = BigInt.zero();
  m.editsApplied = 0;
  m.createdAtBlock = event.block.number;
  m.createdAtTimestamp = event.block.timestamp;
  m.createdAtTx = event.transaction.hash;
  m.save();
}

export function handleSnapshotBatchSubmitted(event: SnapshotBatchSubmitted): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  m.snapshotBatches = m.snapshotBatches + 1;
  m.eligibleSupply = event.params.eligibleSupply;
  m.save();
}

export function handleAddressExcluded(event: AddressExcluded): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  m.excludedCount = m.excludedCount + 1;
  m.save();
}

export function handleSnapshotFinalized(event: SnapshotFinalized): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  m.snapshotFinalized = true;
  m.eligibleSupply = event.params.eligibleSupply;
  m.save();
}

// The event's third argument is named eligibleSupply but carries the new token's whole supply (the old
// token's totalSupply() at approval), so it lands in newTokenSupply here.
export function handleMigrationApproved(event: MigrationApproved): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  let t = newToken(event.params.newToken, "Reliquify", Address.fromBytes(m.leader), Address.fromString("0x3600000000000000000000000000000000000000"), event);
  t.totalSupply = event.params.eligibleSupply;
  t.save();
  m.status = "Live";
  m.token = event.params.newToken;
  m.newTokenSupply = event.params.eligibleSupply;
  m.save();

  DuckTokenTemplate.create(event.params.newToken);
}

export function handleMigrationRejected(event: MigrationRejected): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  m.status = "Rejected";
  m.save();
}

export function handleMigrationAborted(event: MigrationAborted): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  m.status = "Aborted";
  m.save();
}

export function handleDeposited(event: Deposited): void {
  let id = migrationEntityId(event.address, event.params.id);
  let m = ReliquifyMigration.load(id);
  if (m != null) {
    m.totalDeposited = m.totalDeposited.plus(event.params.oldAmount);
    if (event.params.postSeed) {
      m.postSeedDeposited = m.postSeedDeposited.plus(event.params.oldAmount);
    } else {
      m.preSeedDeposited = m.preSeedDeposited.plus(event.params.oldAmount);
      // Same rule as the contract: half of eligibleSupply, rounded down.
      if (!m.thresholdReached && m.totalDeposited.ge(m.eligibleSupply.div(BigInt.fromI32(2)))) m.thresholdReached = true;
    }
    m.save();
  }
  let x = new ReliquifyDeposit(eventId(event));
  x.migration = id;
  x.account = event.params.account;
  x.amount = event.params.oldAmount;
  x.postSeed = event.params.postSeed;
  x.blockNumber = event.block.number;
  x.timestamp = event.block.timestamp;
  x.txHash = event.transaction.hash;
  x.save();
}

export function handleClaimed(event: Claimed): void {
  let id = migrationEntityId(event.address, event.params.id);
  let m = ReliquifyMigration.load(id);
  if (m != null) {
    m.totalClaimed = m.totalClaimed.plus(event.params.amount);
    m.save();
  }
  let x = new ReliquifyClaim(eventId(event));
  x.migration = id;
  x.account = event.params.account;
  x.amount = event.params.amount;
  x.blockNumber = event.block.number;
  x.timestamp = event.block.timestamp;
  x.txHash = event.transaction.hash;
  x.save();
}

export function handleRefunded(event: Refunded): void {
  let id = migrationEntityId(event.address, event.params.id);
  let m = ReliquifyMigration.load(id);
  if (m != null) {
    m.totalRefunded = m.totalRefunded.plus(event.params.amount);
    // Refunds only happen from Aborted, i.e. before the pool exists, so they only ever return pre-seed deposits.
    m.totalDeposited = m.totalDeposited.minus(event.params.amount);
    m.preSeedDeposited = m.preSeedDeposited.minus(event.params.amount);
    m.save();
  }
  let x = new ReliquifyRefund(eventId(event));
  x.migration = id;
  x.account = event.params.account;
  x.amount = event.params.amount;
  x.blockNumber = event.block.number;
  x.timestamp = event.block.timestamp;
  x.txHash = event.transaction.hash;
  x.save();
}

export function handlePoolSeeded(event: PoolSeeded): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  m.status = "Seeded";
  m.poolId = event.params.poolId;
  m.quoteRaised = event.params.quoteRaised;
  m.seededAt = event.block.timestamp;
  m.save();
}

export function handleBuybackBurned(event: BuybackBurned): void {
  let id = migrationEntityId(event.address, event.params.id);
  let m = ReliquifyMigration.load(id);
  if (m != null) {
    m.buybackQuoteSpent = m.buybackQuoteSpent.plus(event.params.quoteIn);
    m.tokensBurned = m.tokensBurned.plus(event.params.burned);
    m.save();
  }
  let x = new ReliquifyBuyback(eventId(event));
  x.migration = id;
  x.quoteIn = event.params.quoteIn;
  x.tokensBurned = event.params.burned;
  x.blockNumber = event.block.number;
  x.timestamp = event.block.timestamp;
  x.txHash = event.transaction.hash;
  x.save();
}

export function handlePausedSet(event: PausedSet): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  m.paused = event.params.paused;
  m.save();
}

// ---- allocation edits, finalize, rescue ----

function loadEdit(m: ReliquifyMigration): ReliquifyAllocationEdit | null {
  let cur = m.currentEdit;
  if (cur == null) return null;
  return ReliquifyAllocationEdit.load(cur as string);
}

export function handleAllocationEditProposed(event: AllocationEditProposed): void {
  let mid = migrationEntityId(event.address, event.params.id);
  let m = ReliquifyMigration.load(mid);
  if (m == null) return;
  let e = new ReliquifyAllocationEdit(mid + "-" + eventId(event).toHexString());
  e.migration = mid;
  e.dataHash = event.params.dataHash;
  e.status = "Proposed";
  e.count = event.params.count.toI32();
  e.readyAt = event.params.readyAt;
  e.accounts = new Array<Bytes>(0);
  e.newCaps = new Array<BigInt>(0);
  e.proposedAt = event.block.timestamp;
  e.proposedTx = event.transaction.hash;
  e.save();
  m.currentEdit = e.id;
  m.save();
}

// Emitted right after AllocationEditProposed, in the same transaction, with the list itself.
export function handleAllocationEditData(event: AllocationEditData): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  let e = loadEdit(m);
  if (e == null) return;
  let accounts = new Array<Bytes>(0);
  for (let i = 0; i < event.params.accounts.length; i++) accounts.push(event.params.accounts[i]);
  e.accounts = accounts;
  e.newCaps = event.params.newCaps;
  e.save();
}

function closeEdit(event: ethereum.Event, id: BigInt, status: string): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, id));
  if (m == null) return;
  let e = loadEdit(m);
  if (e != null) {
    e.status = status;
    e.resolvedAt = event.block.timestamp;
    e.save();
  }
  m.currentEdit = null;
  m.save();
}

export function handleAllocationEditApproved(event: AllocationEditApproved): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  let e = loadEdit(m);
  if (e == null) return;
  e.status = "Approved";
  e.save();
}

export function handleAllocationEditRejected(event: AllocationEditRejected): void {
  closeEdit(event, event.params.id, "Rejected");
}

export function handleAllocationEditCancelled(event: AllocationEditCancelled): void {
  closeEdit(event, event.params.id, "Cancelled");
}

export function handleAllocationEditExpired(event: AllocationEditExpired): void {
  closeEdit(event, event.params.id, "Expired");
}

// Both a leader's applied edit (status Live) and an owner adjustment after the seed emit this.
export function handleAllocationEditApplied(event: AllocationEditApplied): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  m.eligibleSupply = event.params.newEligibleSupply;
  m.editsApplied = m.editsApplied + 1;
  // Lowering allocations can put the pre-seed deposits over half of the new total; the contract flips the flag.
  if (m.status == "Live" && !m.thresholdReached && m.totalDeposited.gt(BigInt.zero())
      && m.totalDeposited.ge(m.eligibleSupply.div(BigInt.fromI32(2)))) m.thresholdReached = true;
  if (m.status == "Live") {
    let e = loadEdit(m);
    if (e != null) {
      e.status = "Applied";
      e.resolvedAt = event.block.timestamp;
      e.appliedBy = event.params.by;
      e.save();
    }
    m.currentEdit = null;
  }
  m.save();
}

export function handleAllocationAdjusted(event: AllocationAdjusted): void {
  let x = new ReliquifyAllocationChange(eventId(event));
  x.migration = migrationEntityId(event.address, event.params.id);
  x.account = event.params.account;
  x.oldCap = event.params.oldCap;
  x.newCap = event.params.newCap;
  x.blockNumber = event.block.number;
  x.timestamp = event.block.timestamp;
  x.txHash = event.transaction.hash;
  x.save();
}

export function handleMigrationFinalized(event: MigrationFinalized): void {
  let m = ReliquifyMigration.load(migrationEntityId(event.address, event.params.id));
  if (m == null) return;
  m.finalized = true;
  m.finalizedAt = event.block.timestamp;
  m.unallocatedAtFinalize = event.params.unallocatedReserve;
  m.save();
}

export function handleReserveRescued(event: ReserveRescued): void {
  let id = migrationEntityId(event.address, event.params.id);
  let m = ReliquifyMigration.load(id);
  if (m != null) {
    m.reserveRescued = m.reserveRescued.plus(event.params.amount);
    m.save();
  }
  let x = new ReliquifyRescue(eventId(event));
  x.migration = id;
  x.to = event.params.to;
  x.amount = event.params.amount;
  x.blockNumber = event.block.number;
  x.timestamp = event.block.timestamp;
  x.txHash = event.transaction.hash;
  x.save();
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleDexConfigSet(event: DexConfigSet): void {
  logAdminEvent(event, CONTRACT, "DexConfigSet", event.params.positionManager.toHexString(), event.params.singleton.toHexString(), event.params.hook.toHexString());
}

export function handleERC20Rescued(event: ERC20Rescued): void {
  logAdminEvent(event, CONTRACT, "ERC20Rescued", event.params.token.toHexString(), event.params.to.toHexString(), event.params.amount.toString());
}

export function handleETHRescued(event: ETHRescued): void {
  logAdminEvent(event, CONTRACT, "ETHRescued", event.params.to.toHexString(), event.params.amount.toString());
}

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleOwnershipTransferStarted(event: OwnershipTransferStarted): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferStarted", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleOwnershipTransferred(event: OwnershipTransferred): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferred", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handlePlatformWalletSet(event: PlatformWalletSet): void {
  logAdminEvent(event, CONTRACT, "PlatformWalletSet", event.params.wallet.toHexString());
}

export function handleReliquifyFeeSet(event: ReliquifyFeeSet): void {
  logAdminEvent(event, CONTRACT, "ReliquifyFeeSet", event.params.fee.toString());
}

export function handleRouteSucceeded(event: RouteSucceeded): void {
  logAdminEvent(event, CONTRACT, "RouteSucceeded", event.params.quoteToken.toHexString(), event.params.routeIndex.toString(), event.params.amountOut.toString());
}

export function handleRoutesSet(event: RoutesSet): void {
  logAdminEvent(event, CONTRACT, "RoutesSet", event.params.quoteToken.toHexString(), event.params.count.toString());
}

export function handleTokenImplSet(event: TokenImplSet): void {
  logAdminEvent(event, CONTRACT, "TokenImplSet", event.params.tokenImpl.toHexString());
}

export function handleUniversalRouterUpdated(event: UniversalRouterUpdated): void {
  logAdminEvent(event, CONTRACT, "UniversalRouterUpdated", event.params.router.toHexString());
}

export function handleUpgraded(event: Upgraded): void {
  logAdminEvent(event, CONTRACT, "Upgraded", event.params.implementation.toHexString());
}

export function handleVaultFactorySet(event: VaultFactorySet): void {
  logAdminEvent(event, CONTRACT, "VaultFactorySet", event.params.vaultFactory.toHexString());
}
